sonar.projectKey=ontsys:go-errchecknext
sonar.projectName=go-errchecknext

sonar.sources=.
sonar.inclusions=**/*.go
sonar.exclusions=**/*_test.go,**/testdata/**/*.go,main.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=test_coverage/**/*.coverprofile
sonar.go.golangci-lint.reportPaths=lint-report-golangci.xml,lint-report-errchecknext.xml
